# FACIAL REGONITION

In [7]:
import cv2

In [8]:
#Read image
img = cv2.imread("/home/prince/Desktop/ngs.jpg")

In [9]:
print(img)

[[[232 234 242]
  [232 234 242]
  [232 234 242]
  ...
  [232 234 242]
  [232 234 242]
  [232 234 242]]

 [[232 234 242]
  [232 234 242]
  [232 234 242]
  ...
  [232 234 242]
  [232 234 242]
  [232 234 242]]

 [[232 234 242]
  [232 234 242]
  [232 234 242]
  ...
  [232 234 242]
  [232 234 242]
  [232 234 242]]

 ...

 [[232 234 242]
  [232 234 242]
  [232 234 242]
  ...
  [232 234 242]
  [232 234 242]
  [232 234 242]]

 [[232 234 242]
  [232 234 242]
  [232 234 242]
  ...
  [232 234 242]
  [232 234 242]
  [232 234 242]]

 [[232 234 242]
  [232 234 242]
  [232 234 242]
  ...
  [232 234 242]
  [232 234 242]
  [232 234 242]]]


In [10]:
print(type(img))

<class 'numpy.ndarray'>


In [11]:
print(img.shape)

(720, 1280, 3)


In [13]:
cv2.imshow("NGS",img)
cv2.waitKey(2000) # time for waiting 2000ms
cv2.destroyAllWindows()  #show image for sometime till presses any keyboard key


In [14]:
resized_img =cv2.resize(img,(600,600))
cv2.imshow("Resize",resized_img)    
cv2.waitKey(2000)
cv2.destroyAllWindows()


In [16]:
resized=cv2.resize(img,(int(img.shape[1]/2),int(img.shape[0]/2)))
cv2.imshow("Resized",resized)    
cv2.waitKey(2000)
cv2.destroyAllWindows()    
